### ISSUE TITLE
KeyError: "['TP_PRESENCA_MT'] not in index"

### ISSUE THREAD

**Issue by OtacilioN** [lauraDamacenoAlmeida/Enem_2016#1]
Olá Laura,

Primeiro gostaria de parabenizar pelo artigo do Medium, cheguei no projeto por lá. Percebi que no finalzinho do código contém o seguinte erro:

> KeyError: "['TP_PRESENCA_MT'] not in index"

Investigando, percebi que isso acontece pois o arquivo "test.csv" não possui essa coluna, porém analisando a matriz de correlação, dá pra ver que a coluna TP_PRESENCA_MT tem correlação de 1 com a coluna TP_PRESENCA_LC.

Portanto vou submeter um pull request realizando essa correção, com a troca do TP_PRESENCA_MT para TP_PRESENCA_LC na base de teste.

**Comment by lauraDamacenoAlmeida** [comment]
Obrigada @OtacilioN pela contribuição, eu nem tinha visto esse erro. Aceitei seu PR =)
